### ISSUE TITLE
osc staging select no longer works on Leap 15.3

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2770]
```
> osc staging select C file bash
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 347, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/dimstar_suse/.osc-plugins/osc-staging.py", line 571, in do_staging
    filter_from, no_freeze=opts.no_freeze, remove_exclusion=opts.remove_exclusion)
  File "/home/dimstar_suse/.osc-plugins/osclib/select_command.py", line 123, in perform
    if not (no_freeze or self.api.prj_frozen_enough(self.target_project)):
  File "/home/dimstar_suse/.osc-plugins/osclib/stagingapi.py", line 1183, in prj_frozen_enough
    if self.days_since_last_freeze(project) < MAX_FROZEN_AGE:
  File "/home/dimstar_suse/.osc-plugins/osclib/stagingapi.py", line 884, in days_since_last_freeze
    freezetime = datetime.fromisoformat(freezetime)
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by coolo** [comment]
`New in version 3.7.` 
![](https://c.tenor.com/vQMltVVcsPsAAAAC/cat-annoyed.gif)
